import type { Currency } from '@coinfrenzy/config'

// Types per docs/04 §2-§4. Every ledger write is described as a
// TransactionSpec (a `pair_id` group of entries) and the write path returns a
// LedgerWriteResult discriminated on { status }.

export type LedgerLeg = 'debit' | 'credit'

export type SubBucket = 'purchased' | 'bonus' | 'promo' | 'earned'

export type LedgerSource =
  | 'purchase'
  | 'bet'
  | 'win'
  | 'bonus_award'
  | 'playthrough_release'
  | 'redemption_request'
  | 'redemption_paid'
  | 'redemption_rejected'
  | 'purchase_refund'
  | 'admin_adjustment'
  | 'affiliate_payout'
  | 'bonus_expired'
  | 'migration'

// docs/04 §2 — the typed account model. account_kind = enum, account_id = uuid.
// account_id meaning per kind:
//   player_wallet           -> wallets.id
//   pending_purchase        -> players.id
//   pending_redemption      -> players.id
//   house_*, bonus_pool_*,
//   amoe_pool_sc,
//   affiliate_payable,
//   internal_account_sink,
//   external                -> house_accounts.id (resolved at write time)
export type LedgerAccountKind =
  | 'player_wallet'
  | 'pending_purchase'
  | 'pending_redemption'
  | 'house_bank'
  | 'house_winnings_gc'
  | 'house_winnings_sc'
  | 'bonus_pool_gc'
  | 'bonus_pool_sc'
  | 'amoe_pool_sc'
  | 'affiliate_payable'
  | 'internal_account_sink'
  | 'external'

/**
 * A single planned entry. account_id is OPTIONAL on the spec — for house
 * accounts the write path resolves it via the (kind, currency) lookup, and
 * for player accounts the caller supplies player_id and the write path
 * resolves it to the matching wallets.id. This keeps transaction builders
 * decoupled from house_accounts row IDs.
 */
export interface EntrySpec {
  leg: LedgerLeg
  accountKind: LedgerAccountKind
  /** Pre-resolved account ID. If omitted, the writer resolves from accountKind+playerId+currency. */
  accountId?: string
  /** Always positive — leg encodes direction. Bigint in minor units. */
  amount: bigint
  currency: Currency
  /** Only set for player_wallet entries (and admin adjustments). */
  subBucket?: SubBucket | null
  /** When the entry hits a player-owned account, populate the player id for fast lookups. */
  playerId?: string | null
  metadata?: Record<string, unknown>
}

/**
 * The atomic unit of a ledger write. All entries are inserted in one
 * Postgres transaction and share one pair_id (generated by the writer).
 */
export interface TransactionSpec {
  source: LedgerSource
  /** Stable, idempotent external/internal id (e.g. Finix transfer.id or our uuid). */
  sourceId: string
  /** Free-form key the upstream caller may inject. We persist it on every entry. */
  idempotencyKey?: string | null
  /** The player this transaction is about (used to invalidate caches + populate player_id). */
  playerId?: string | null
  entries: EntrySpec[]
  /** Anything you want attached to every leg's metadata field (e.g. round_id, game_id). */
  metadata?: Record<string, unknown>
}

/** Subset of a ledger_entries row returned by the writer. */
export interface InsertedLedgerEntry {
  id: string
  source: LedgerSource
  sourceId: string
  pairId: string
  leg: LedgerLeg
  accountKind: LedgerAccountKind
  accountId: string
  amount: bigint
  currency: Currency
  subBucket: SubBucket | null
  playerId: string | null
  balanceAfter: bigint | null
  createdAt: Date
}

export type LedgerWriteResult =
  | { status: 'written'; pairId: string; entries: InsertedLedgerEntry[] }
  | { status: 'duplicate'; noop: true }
